FROM openjdk:17-oracle
COPY target/currency-conversion-service-0.0.1-SNAPSHOT.jar currency-conversion-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/currency-conversion-service-0.0.1-SNAPSHOT.jar"]