
FROM openjdk:17-oracle
COPY target/currency-exchange-service-0.0.1-SNAPSHOT.jar currency-exchange-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/currency-exchange-service-0.0.1-SNAPSHOT.jar"]